### ISSUE TITLE
please add support laravel mix 4

### ISSUE THREAD

**Issue by vahidalvandi** [KABBOUCHI/laravel-mix-merge-manifest#3]

**Comment by KABBOUCHI** [comment]
PR #1 fixed the issue, please try v0.1.2

**Comment by vahidalvandi** [comment]
thank you

**Comment by vahidalvandi** [comment]
why it not work version(); ?

**Comment by KABBOUCHI** [comment]
I tested it, its fine work with mix v2 and v4, make sure you are installing the latest version
